### ISSUE TITLE
Error parsing JSON in live demo

### ISSUE THREAD

**Issue by hichemfantar** [juanjoDiaz/json2csv#43]
1. [Live demo](https://juanjodiaz.github.io/json2csv/#/live).
2. Chrome 114.
Used input:
```json
[
    {
        "businessName": "Google"
    }
]
```
Console error:
```
vue.global.js:1694 Uncaught ReferenceError: Json2csvStreamParser is not defined
    at Proxy.parseJSON ((index):136:30)
    at callWithErrorHandling (vue.global.js:1631:20)
    at callWithAsyncErrorHandling (vue.global.js:1639:19)
    at HTMLButtonElement.invoker (vue.global.js:9371:7)
```

**Comment by juanjoDiaz** [comment]
This took long enough... But it's fixed in 7.0.3
